---
# tasks file for provision-alveo
- name: Install XRT on ubuntu18
  apt:
     deb: '{{ base_url }}{{ xrt_package_ubuntu18 }}'
     state: present
  when: install_xrt
     
- name: Install U280 on ubuntu18
  yum:
     deb: '{{ base_url }}{{ U280_package_ubuntu18 }}'
     state: present
  when: install_U280

- name: Install U250 on ubuntu18
  yum:
     deb: '{{ base_url }}{{ U250_package_ubuntu18 }}'
     state: present
  when: install_U250

- name: Install U200 on ubuntu18
  yum:
     deb: '{{ base_url }}{{ U200_package_ubuntu18 }}'
     state: present
  when: install_U200

- name: Install U50 on ubuntu18
  yum:
     deb: '{{ base_url }}{{ U50_package_ubuntu18 }}'
     state: present
  when: install_U50

